name: Prepare project release
on:
  push:
    branches: master   

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    
    name: Prepare release
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11.0.18+10'         
      - uses: s4u/setup-maven-action@v1.2.1
        with:
          java-version: '11.0.18+10' 
          maven-version: '3.3.9'
      - name: Configure Git release
        run: |         
          git config user.email "nk.patidar01@gmail.com"
          git config user.name "nandkishore-patidar"         
          git fetch origin
          git checkout master
          git reset --hard origin/master
          git pull origin master --allow-unrelated-histories
          mvn --batch-mode gitflow:release        
     
        env:
          GITHUB_TOKEN: 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
          
          
